### ISSUE TITLE
Breadcrumb apariencia

### ISSUE THREAD

**Issue by antvaleria** [hacklabcbba/telartes#1]
![breadcrumb](https://cloud.githubusercontent.com/assets/13840657/9358999/e588652a-465c-11e5-8cd5-dea7fae55dad.png)
Adjunto dejo el diseño
![breadcrumb dg](https://cloud.githubusercontent.com/assets/13840657/9359020/00ad5680-465d-11e5-8342-562aec32df7a.png)

**Comment by danicotillas** [comment]
@jgenso aquí ya vamos empezando con las aperturas de tickets.
@antvaleria es Vale, responsable de Comunicación Visual de Telartes que creo ya conoces y @FabyQuiroga la Faby que sí conoces de sobra.

Gracias!

**Comment by marcelorodcla** [comment]
@antvaleria  Listo. Revisar y cerrar el ticket por favor.
