### ISSUE TITLE
Reeemplazar banner en el home

### ISSUE THREAD

**Issue by antvaleria** [hacklabcbba/telartes#11]
@jgenso @Cesarluis Reemplazar banner del menú con links "flotantes" en el home por esta imagen compartida en el Drive:
https://drive.google.com/drive/folders/0Bxg1HTzPj3EofkRWaHg3NjNieW1MZGt6WUNXQlVDQmgxSEpfaDB6RzFlc2hrSXh1aTRmdms

**Comment by marcelorodcla** [comment]
@antvaleria  Al parecer el banner ya fue remplazado, creo que este issue podría cerrarse.
