### ISSUE TITLE
Reubicar links flotantes sobre banner en el home

### ISSUE THREAD

**Issue by antvaleria** [hacklabcbba/telartes#12]
@jgenso @Cesarluis sería bueno reubicar los links flotantes sobre el nuevo banner como se muestra en la imagen, los links están coincidiendo con algunas estrellas que conforman una constelación andina en forma de rueca. También es importante el orden en el que están.
![banner-30-julio](https://cloud.githubusercontent.com/assets/13840657/9370246/d5065c8a-469c-11e5-8b1b-6f38bc2a5638.png)

**Comment by marcelorodcla** [comment]
@antvaleria  Se a dispuesto los elementos en el orden y posición de la imagen de la imagen, no obsante en la base de datos que me fue proporcionada falta la opción "Sostenibilidad" y "Circulación cultural" esta como "Economia colaborativa".

**Comment by marcelorodcla** [comment]
hecho
