### ISSUE TITLE
Enlaces flotantes banner: Aumentar dimensión de fuente

### ISSUE THREAD

**Issue by antvaleria** [hacklabcbba/telartes#13]
@jgenso @Cesarluis 
En lo posible aumentar la dimensión de la fuente tipográfica de los enlaces flotantes en el banner, puede ser uno o dos puntos más grande de la fuente actual, en una open sans semibold, para unificar con el resto del sitio (en caso de trabajar el replanteamiento de la fuente tipográfica - Isuue#3)

**Comment by marcelorodcla** [comment]
@antvaleria Se aumentó el tamaño de la fuente y se cambio la tipografia a open sans semibold

**Comment by antvaleria** [comment]
@marcelorodcla un favor si se puede reducir un poco la fuente de los enlaces flotantes, que esté un poco más grande que los enlaces del header pero no tanto, me parece que está un poco grande.

**Comment by marcelorodcla** [comment]
Listo
