### ISSUE TITLE
Enlaces flotantes banner: editar texto de enlaces

### ISSUE THREAD

**Issue by antvaleria** [hacklabcbba/telartes#14]
@jgenso @Cesarluis 
En los enlaces flotantes del banner del home se deben hacer algunas modificaciones en el texto, aumentar enlaces y sub-enlaces también:
1. Agregar enlace de "Circulación Cultural" con sub-enlace a "Hospeda Cultura" (https://docs.google.com/a/telartes.org.bo/forms/d/1Il8KOf-xWcaR0thqhWHF0YzAq3KUuo7pH4Y5gKyUeNI/viewform)
2. Denominación de "Economía Colaborativa" se cambia por "Sostenibilidad"
3. Quitar sub-enlace de "Hospeda cultura" en "Economía Colaborativa"
4. "Sostenibilidad" con sub-enlace a "Banco de Recursos 4D" (página por crear) y "Minka" (http://minka.me/)
5. "Incidencia" con sub-enlace a "Abre Cultura". (http://abrecultura.org/)
-Adjunto imagen del diseño del banner-
![banner-30-julio](https://cloud.githubusercontent.com/assets/13840657/9370904/0dde3e1a-46a2-11e5-8336-9647c08c1c51.png)

**Comment by marcelorodcla** [comment]
@Cesarluis Favor pasarme la DB cuando los cambios se hayan realizado

**Comment by Cesarluis** [comment]
@antvaleria @marcelorodcla modifique el menu flotante, en este caso lo programaron en un archivo del theme, o sea que actualizando el github ya lo tienes @marcelorodcla. De todas maneras te enviare una actualizacion del sitio.

**Comment by marcelorodcla** [comment]
Hecho

**Comment by marcelorodcla** [comment]
@antvaleria  Cerrar el ticket por favor.
