### ISSUE TITLE
Circulación Cultural: trabajo general de armado de la página

### ISSUE THREAD

**Issue by antvaleria** [hacklabcbba/telartes#15]
@jgenso @Cesarluis Entre ayer y hoy Cesar estuvo avanzando la inserción de las diferentes galerías a las páginas del sitio. Así es cómo luce Circulación Cultural ahora, hice unas pequeñas observaciones en la imagen, pero en general es trabajo de hojas de estilo me parece.
![circulacion cultural](https://cloud.githubusercontent.com/assets/13840657/9394861/c4a5fee2-4758-11e5-961d-4714abda7608.png)
-Adjunto diseño de esta página-
![circulacion cultural](https://cloud.githubusercontent.com/assets/13840657/9394879/ea0e0be8-4758-11e5-890e-9c653f03e12e.jpg)

**Comment by marcelorodcla** [comment]
@antvaleria Se quitó el borde, las galerias se mantendrá fijas si se configura en el administrador de contendos.

**Comment by marcelorodcla** [comment]
es necesario hacer algunas modificaciones en los view, a través del administrador

**Comment by marcelorodcla** [comment]
@antvaleria @Cesarluis  Listo. En el administrador, en la edición de la Vista, cambiar el Formato a Lista sin formato. Luego de revisar, si corresponde, favor cerrar el ticket.

**Comment by antvaleria** [comment]
@marcelorodcla para cerrar este issue faltaría el trabajo de estilos en lo que son las galerías, se está jalando el contenido y las galerías ya son fijas (antes estaban como desplegables), pero faltaría acomodar dimensión de imágenes, tipografía, el ícono que viene sobre cada imagen según el tipo de contenido (si es noticia, agenda cultural, convocatoria, etc) y esos detalles, por favor fíjate en el diseño que dejé en el primer comentario. Este mensaje se aplica a los issues: 4, 5, 9, 15, 16, 17, y 18
![circulacion cultural telartes](https://cloud.githubusercontent.com/assets/13840657/9723175/7835992a-5589-11e5-8cad-dfe5adbe40db.png)
Adjunto una visualización de la especificación de fuentes tipográficas la medida está en pts. 
![incidencia tipografia](https://cloud.githubusercontent.com/assets/13840657/9723278/fc02dcc0-558b-11e5-9ea7-8476bfcef702.jpg)
Equivalente de pts. a pxs.
OPEN SANS
10 pt. = 13px (fecha, hora, subido por en previsualizaciones | Breadcrumb)
10.5 pt = 14px (texto menú header)
13 pt. = 17px (títulos de subcontenidos)
16 pt. = 22px (Subtítulos)
22 pt. = 29px (Títulos)
GARAMOND

12 pt. = 16px (Cuerpo de texto de un subcontenido o previsualización)
16 pt. = 22px (Cuerpo principal de texto)

**Comment by marcelorodcla** [comment]
@antvaleria faltaba cambiar el formato de salida de la view, ya está. La tipografía ya está. Favor revisar.

**Comment by antvaleria** [comment]
@marcelorodcla ya todo está agarrando forma, creo que ahora es un trabajo de ir afinando detalles en algunas páginas del sitio te dejo una captura de pantalla con algunas observaciones para ir corrigiendo, estas observaciones se aplican a todas las páginas que presentan este tipo de contenido es decir todas las páginas que tienen galerías y todas las páginas que tiene la sección de "lo más destacado"
![circulacion cultural telartes1](https://cloud.githubusercontent.com/assets/13840657/9748676/78987916-5654-11e5-942c-2192f4c7ad4b.png)

**Comment by marcelorodcla** [comment]
@antvaleria lo siento, me olvidé reportar. Ya está.

**Comment by antvaleria** [comment]
@marcelorodcla @Cesarluis Dejo algunos apuntes para ir trabajando sobre lo que son estilos, principalmente de las visualizaciones de los contenidos de las galerías. Esta página http://telartes.barriohacker.net/content/circulacion tiene todos los tipos de contenidos para ir trabajando estilos, mantengamos como referencia el diseño que está adjunto en el primer comentario de este issue para ir comparando apariencias.
![circulacion cultural telartes2](https://cloud.githubusercontent.com/assets/13840657/9964616/59e97968-5dff-11e5-9fea-361fed398080.png)
