### ISSUE TITLE
Cultura Viva Comunitaria - Formulario Edición: Cuadro de enlaces a articulaciones y enlaces

### ISSUE THREAD

**Issue by antvaleria** [hacklabcbba/telartes#19]
@jgenso @Cesarluis En el formulario de edición de la página de Cultura Viva Comunitaria, en la sección para ingresar enlaces a Enlaces y Articulaciones, hay algunas limitantes que van a impedir que la información de visualice como en el diseño, en la imagen están anotados los puntos.
![cultura viva comunitaria formulario](https://cloud.githubusercontent.com/assets/13840657/9410307/921b3ec0-47ed-11e5-8e8f-8834074b838b.png)
-Adjunto diseño de cómo debería verse la información una vez subida al formulario y guardada (el texto en lila es un enlace al sitio correspondiente-
![cultura viva comunitaria formulario dg](https://cloud.githubusercontent.com/assets/13840657/9410363/e13cf228-47ed-11e5-8851-1c37e7875839.png)

**Comment by Cesarluis** [comment]
El formulario de enlaces ya tiene descripción
