### ISSUE TITLE
Cambiar color del fondo menú header

### ISSUE THREAD

**Issue by antvaleria** [hacklabcbba/telartes#2]
![header1](https://cloud.githubusercontent.com/assets/13840657/9359178/c35e6de0-465d-11e5-9746-a1a8853afbb8.png)
@jgenso Se podría cambiar el color del fondo del menú del header por un gris más claro (incluye la sección del usuario) y el texto que va por encima debe ir en un gris más oscuro (#404041 este o uno aproximado)no negro.
-Adjunto diseño-
![header](https://cloud.githubusercontent.com/assets/13840657/9359229/2d9dce30-465e-11e5-91c9-6841ef15b8b5.png)

**Comment by marcelorodcla** [comment]
hecho
