### ISSUE TITLE
Cultura de Red - Formulario Edición: 

### ISSUE THREAD

**Issue by antvaleria** [hacklabcbba/telartes#20]
@jgenso @Cesarluis En el formulario de edición de la página de Cultura de Red, en la sección para ingresar enlaces a Enlaces y Articulaciones, sería bueno ingresar un espacio para ingresa un descripción.
![cultura de red formulario](https://cloud.githubusercontent.com/assets/13840657/9410608/1f6db45a-47ef-11e5-8e00-8c3143593f10.png)
-Adjunto diseño de cómo debería verse la información una vez subida al formulario y guardada (el texto en lila es un enlace al sitio correspondiente-
![cultura viva comunitaria formulario dg](https://cloud.githubusercontent.com/assets/13840657/9410615/271232da-47ef-11e5-9246-a640b2c260df.png)

**Comment by Cesarluis** [comment]
Se ha añadido el campo descripción
