### ISSUE TITLE
Actorxs Culturales - Previsualización usuarios: previsualización de nombre completo y denomincación

### ISSUE THREAD

**Issue by antvaleria** [hacklabcbba/telartes#24]
@Cesarluis En las previsualizaciones de los perfiles de usuarios, redes y colectivos, falta "llamar" la siguiente información.
- Personal/Individual: Debajo del nombre de usuario podría aparecer el nombre y apellido(s) que llenó en formulario de registro
- Colectivo/Institución  y  Red/Articulación: Debajo del nombre podría mostrarse la "denominación" del perfil correspondiente, por ejemplo Hack Lab se registró como un Colectivo/Institución
  ![actorxs culturales denominaciones](https://cloud.githubusercontent.com/assets/13840657/9481425/21b7a34e-4b58-11e5-9d03-4b388b4f23f5.png)

-Adjunto diseño-
![actorxs culturales denominaciones dg](https://cloud.githubusercontent.com/assets/13840657/9481461/7c2e0f7a-4b58-11e5-84af-5ea087b86c8c.png)

**Comment by marcelorodcla** [comment]
Falta definir tipográfia y máximo de caracteres en cada campo.

**Comment by marcelorodcla** [comment]
Falta definir sobre los campos de intereses, áreas. Éstos puede variar según el perfil definir que sucederá en esos casos; por ahora como en el diseño todos las cajas tiene una altura fija, los perfiles que tengan mayor textos salen cortados.

**Comment by marcelorodcla** [comment]
@antvaleria  Listo, favor cerrar el ticket.

**Comment by antvaleria** [comment]
@marcelorodcla la info ya va teniendo forma, dejo algunas observaciones para ir afinando y que se parezca más al diseño
![actorxs culturales telartes](https://cloud.githubusercontent.com/assets/13840657/9723528/3b8da7ee-5591-11e5-9368-daa0be9c2481.png)
