### ISSUE TITLE
Actorxs Culturales: Reemplazar iconos genéricos de usuarios

### ISSUE THREAD

**Issue by antvaleria** [hacklabcbba/telartes#25]
@jgenso @Cesarluis @marcelorodcla En las previsualizaciones de los perfiles de usuarios redes y colectivos en "Actorxs Culturales" si se pueden reemplazar los iconos genéricos, de aquellos perfiles que no subieron fotografía en su registro, sería muy bueno porque actualmente el icono que se tiene del hombresito con las líneas de colores es un poco estridente visualmente.
Les dejo link para descargar los iconos compartidos desde el drive: https://drive.google.com/drive/folders/0Bxg1HTzPj3EoflJJMElJci1FU3NIelBSV0RfUWtWRjV2MDUtQWV4YXdCM3lHU3JxN2l4eG8
![actorxs culturales iconos](https://cloud.githubusercontent.com/assets/13840657/9481951/f4dc2638-4b5c-11e5-8d7d-a68fe25212bf.png)
-Adjunto diseño de las previsualizaciones de los perfiles- 
![actorxs culturales denominaciones dg](https://cloud.githubusercontent.com/assets/13840657/9481985/3193b140-4b5d-11e5-8205-929f91539832.png)

**Comment by Cesarluis** [comment]
Acabo de cambiar los iconos por defecto

**Comment by Cesarluis** [comment]
He reordenado los campos de cada elemento, indicando la fotografía en primera posición

**Comment by antvaleria** [comment]
@Cesarluis un favor, se veía mejor en dos columnas, si podemos volver a eso sería bueno.

**Comment by antvaleria** [comment]
@Cesarluis  los iconos y espacio para la foto de perfil es a 69px x 69px, ahora está a 64px x 64px. Si lo puedes reajustar por favor.

**Comment by Cesarluis** [comment]
ya esta en el tamaño que pides, @marcelorodcla ahora toca una manito de estilos ...
