### ISSUE TITLE
Qué somos y Manifiesto: Quitar enlaces al final de la página

### ISSUE THREAD

**Issue by antvaleria** [hacklabcbba/telartes#27]
@Cesarluis al final de la página de "Qué somos" y "Manifiesto" hay cinco enlaces (Formación, Comunicación, Incidencia, Economía Colaborativa, Circulación Cultural) esos enlaces se deben quitar de ambas páginas.
![quitar enlaces](https://cloud.githubusercontent.com/assets/13840657/9497628/e7e4c5d4-4be3-11e5-9161-27b8a1aa08fc.png)

**Comment by Cesarluis** [comment]
esto ya esta
