### ISSUE TITLE
Menú Desplegable/ Editorial

### ISSUE THREAD

**Issue by antvaleria** [hacklabcbba/telartes#33]
@marcelorodcla  arreglar la apariencia de Editorial.
![Uploading Usuario   telartes.png…]()

**Comment by FabyQuiroga** [comment]
@marcelorodcla mando la captura de pantalla, el editorial está desconfigurado.

![usuario telartes](https://cloud.githubusercontent.com/assets/13841602/9588824/602486d4-4ff8-11e5-9aa8-23134e2bdbb8.png)

**Comment by marcelorodcla** [comment]
@antvaleria Listo. Favor cerrar el ticket
