### ISSUE TITLE
Agenda Cultura - Desplegable: No se visualizan contenidos

### ISSUE THREAD

**Issue by antvaleria** [hacklabcbba/telartes#38]
@marcelorodcla @Cesarluis Chicos por favor revisen esta parte, desde hace algún tiempo no se está mostrando las previsualizaciones de la Agenda Cultural, revisen eso por favor.
![agenda cultural deplegable](https://cloud.githubusercontent.com/assets/13840657/9736326/7e7a7de8-560e-11e5-958c-0d035a57b240.png)

**Comment by marcelorodcla** [comment]
@antvaleria listo, favor revisar.
