### ISSUE TITLE
Noticias - Desplegable: Corregir espacio entre recuadros de previsualizaciones

### ISSUE THREAD

**Issue by antvaleria** [hacklabcbba/telartes#39]
@marcelorodcla @Cesarluis Las previsualizaciones de noticias en el desplegable del home se movieron hace algunos días, por favor revisen eso porque era algo que ya estaba bien acomodado.
![noticia deplegable](https://cloud.githubusercontent.com/assets/13840657/9775772/e95623ee-571f-11e5-929c-e30ce07c5a90.png)

**Comment by marcelorodcla** [comment]
@antvaleria Listo, esta igual que agenda cultural. Favor revisar.
