### ISSUE TITLE
Comunicación - Formulario Edición: Cuadro de enlaces a Radios Comunitarias y Articulaciones

### ISSUE THREAD

**Issue by antvaleria** [hacklabcbba/telartes#6]
@jgenso @Cesarluis En el formulario de edición de la página de Comunicación, en la sección para ingresar enlaces a Radios Comunitarias y Articulaciones, hay algunas limitantes que van a impedir que  la información de visualice como en el diseño, en la imagen están anotados los puntos.
![formulario comunicacion enlaces](https://cloud.githubusercontent.com/assets/13840657/9366531/fd39df22-4685-11e5-8c7e-0e951c5a41f7.png)
-Adjunto diseño de cómo debería verse la información una vez subida al formulario y guardada (el texto en lila es un enlace al sitio correspondiente-
![formulario comunicacion enlaces dg](https://cloud.githubusercontent.com/assets/13840657/9366558/25d71788-4686-11e5-9618-96c3724ce655.png)

**Comment by Cesarluis** [comment]
@antvaleria ya esta el formulario, solo faltan los estilos
