### ISSUE TITLE
Incidencia - Formulario Edición: Cuadro de enlaces a Incidencia en Políticas Culturales

### ISSUE THREAD

**Issue by antvaleria** [hacklabcbba/telartes#7]
@jgenso @Cesarluis En el formulario de edición de la página de Incidencia, en la sección para ingresar enlaces a Incidencia en Políticas Culturales, hay algunas limitantes que van a impedir que la información de visualice como en el diseño, en la imagen están anotados los puntos.
![incidencia fromulario enlaces](https://cloud.githubusercontent.com/assets/13840657/9366972/71f21486-4688-11e5-934c-2062d542cb19.png)
-Adjunto diseño de cómo debería verse la información una vez subida al formulario y guardada (el texto en lila es un enlace al sitio correspondiente-
![incidencia fromulario enlaces dg](https://cloud.githubusercontent.com/assets/13840657/9366978/7e0f7c04-4688-11e5-8a42-d24bf4cf86b9.png)

**Comment by Cesarluis** [comment]
@antvaleria ya esta el formulario, solo faltan estilos

**Comment by Cesarluis** [comment]
El formulario ya esta corregido, falta el css en la visualizacion @marcelorodcla

**Comment by jgenso** [comment]
ok, marcelo esta de viaje asi que tiene conexion limitada estara de vuelta
el sabado.

2015-09-02 16:13 GMT-04:00 Cesarluis notifications@github.com:

> El formulario ya esta corregido, falta el css en la visualizacion
> @marcelorodcla https://github.com/marcelorodcla
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hacklabcbba/telartes/issues/7#issuecomment-137230179.

## 

*Juan Jose Olivera Rodriguez Genso Iniciativas Web +591.44505438 *
