### ISSUE TITLE
Formación - Formulario Edición: Cuadro de enlaces a Articulaciones

### ISSUE THREAD

**Issue by antvaleria** [hacklabcbba/telartes#8]
@jgenso @Cesarluis En el formulario de edición de la página de Incidencia, en la sección para ingresar enlaces a Articulaciones, hay algunas limitantes que van a impedir que la información de visualice como en el diseño, en la imagen están anotados los puntos.
![formulario formacion enlaces](https://cloud.githubusercontent.com/assets/13840657/9367232/2d31c808-468a-11e5-9e44-ec6ac892bf7b.png)
-Adjunto diseño de cómo debería verse la información una vez subida al formulario y guardada (el texto en lila es un enlace al sitio correspondiente-
![formulario formacion enlaces dg](https://cloud.githubusercontent.com/assets/13840657/9367259/455a7060-468a-11e5-8612-e5abae5be2ed.png)

**Comment by Cesarluis** [comment]
@antvaleria este ya esta
